NAME = Queen-Padme-Tales--Nighttime-Flight Queen-Padme-Tales--Planting-Trees Queen-Padme-Tales--Queen-Amidala-vs-the-Klingon-Warriors Queen-Padme-Tales--Take-It-Over Queen-Padme-Tales--The-Fifth-Sith

DOCS_BASE = $(NAME)

SELINA_UPLOAD_TEMP_DEST = temp-queen-padme-tales

include $(SCREENPLAY_COMMON_INC_DIR)/screenplays_common.mak

